spring:
  application:
    name: springboot_demo

  datasource:
    url: jdbc:mysql://localhost:3306/dbtest
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: itshuaan@gmail.com
    password: ckeyvntiacdyhwrb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  SECRET_KEY: askhdqiwu48123y123cxv2134123/123u1t238gqhjwdnjaqwhuie412/312i3o1y28712iekjasbdiuqw9e812739jasldk/zxkcbaskanskdlasda/scaksjcoiasjdoi12312o123/qwkjehqwuiehjiqwueiqwuejkqwndoqwd/129831yu293h12ui3qhwiuehqwuieiwheiqwe
  JWT_EXPIRATION: 28800000
